apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-notificaciones-deployment
  labels:
    app: ms-notificaciones
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ms-notificaciones
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: ms-notificaciones
    spec:
      containers:
        - name: ms-notificaciones
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PORT
              value: {{ .Values.env.PORT | quote }}
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.rabbitmqSecretName }}
                  key: {{ .Values.rabbitMq.urlKey }}
