apiVersion: v1
kind: Service
metadata:
  name: ms-notificaciones-service
  labels:
    app: ms-notificaciones
spec:
  selector:
    app: ms-notificaciones
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
