apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    JWT_SECRET: AgBEnUVYg9hQuirCcB47zXQkjOEOWDrVdUeOvx5wIfapHc0V+OGxJTTymp9MDSIea//+gfrQFMjpyWIAcLL9K4U9CTbfdnRsLpGKvqOxxnkYGfCTiEq5mjQ8Ud+VHRmnQ/KgflMsJrLQy0GMqVL51o9nSANFKU0pHtuRav3jhOc+AyfxwaaXkKPevDJIJyxY4r85viCooCl1mfPfJ6lZvoXeHNkp7GxSvqdMPOSS6QGgGKLfaJpCwFxDcoTEpeJufsavDfdg15YDTGl2Vw2On9oX9dlqfuqoC/WMvZRGm4A36DFaQpYhnCmKk9tRSD2MdIxnrHmXkcQj75JxJpem2LD8CJ/57QKfE6h0TerGHS/uTAa3ewnKLtrMIlh5T9SZkcwMzAoWj3aiR48DQClMlDdWuBW8krhcA7V3x/mm/9HSQYSYhWprjcFU/WibM51KukX4eJ4s0U1XpwiVDYwCBtm+9RDI64gDAavaGdNSIVkNBtY24PQ97XDLMa56llUE2B86RXo1togKQNMCeNR1lKSTbLD5VttOn6uJK+TeLv7axjlbbIwJDdOaGoQYL3IUbH2TqkXGx7IANkvqikTINPygOGGv4Oeu6MgNuX5PDrSmPo4CSB2pdNsBHdFF9jsCvr+L31bSewZImcK8P+y1YqDEzbap49+aolFjY3RnlrQo94UzX+uOGhK0rS6nSzFUMHFQ4CF1CcCuGD+plCabrg8H7w==
  template:
    metadata:
      name: jwt-secret
      namespace: {{ .Release.Namespace }}
