# kubernetes-manifests/protected-ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          # Auth (login) -> ms-auth
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: ms-auth-service
                port:
                  number: 4000

          # Orquestador de tutor√≠as
          - path: /tutorias
            pathType: Prefix
            backend:
              service:
                name: ms-tutorias-service
                port:
                  number: 3000

          # Usuarios
          - path: /usuarios
            pathType: Prefix
            backend:
              service:
                name: ms-usuarios-service
                port:
                  number: 3001

          # Agenda
          - path: /agenda
            pathType: Prefix
            backend:
              service:
                name: ms-agenda-service
                port:
                  number: 3002

          # Notificaciones
          - path: /notificaciones
            pathType: Prefix
            backend:
              service:
                name: ms-notificaciones-service
                port:
                  number: 3003
