apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: jwt-validation-plugin
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: ms-auth-service
                port:
                  number: 4000
          - path: /tutorias
            pathType: Prefix
            backend:
              service:
                name: ms-tutorias-service
                port:
                  number: 3000
          - path: /usuarios
            pathType: Prefix
            backend:
              service:
                name: ms-usuarios-service
                port:
                  number: 3001
          - path: /agenda
            pathType: Prefix
            backend:
              service:
                name: ms-agenda-service
                port:
                  number: 3002
          - path: /notificaciones
            pathType: Prefix
            backend:
              service:
                name: ms-notificaciones-service
                port:
                  number: 3003
