apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-ingress
  annotations:
    konghq.com/strip-path: "true"
    konghq.com/plugins: rate-limiting-5pm
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /client
            pathType: Prefix
            backend:
              service:
                name: client-mobile-sim-service
                port:
                  number: 8080
          - path: /tracking
            pathType: Prefix
            backend:
              service:
                name: tracking-dashboard-service
                port:
                  number: 9000
