apiVersion: v1
kind: Service
metadata:
  name: ms-agenda-service
  labels:
    app: ms-agenda
spec:
  selector:
    app: ms-agenda
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
