apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-mobile-sim-deployment
  labels:
    app: client-mobile-sim
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: client-mobile-sim
  template:
    metadata:
      labels:
        app: client-mobile-sim
    spec:
      containers:
        - name: client-mobile-sim
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: API_BASE_URL
              value: {{ .Values.env.API_BASE_URL | quote }}
            - name: AUTH_SERVICE_URL
              value: {{ .Values.env.AUTH_SERVICE_URL | quote }}
