apiVersion: v1
kind: Service
metadata:
  name: client-mobile-sim-service
  labels:
    app: client-mobile-sim
spec:
  selector:
    app: client-mobile-sim
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
