apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tutorias-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HebertCG/RETO7.git
    targetRevision: main
    path: charts/tutorias-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: tutorias
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
