apiVersion: v1
kind: Service
metadata:
  name: ms-auth-service
  labels:
    app: ms-auth
spec:
  selector:
    app: ms-auth
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
