apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-usuarios
  labels:
    app: db-usuarios
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-agenda
  labels:
    app: db-agenda
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-tutorias
  labels:
    app: db-tutorias
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
